
<html>
  <head>
    <title>Lab 08 - Graded Solution</title>
  </head>
  <body>
    <h1>Lab 08 - Graded Solution</h1>
    <p><b>You scored 0% = 0.0 points for this lab.</b></p>
    <ul>
      <li><b>test_key_heap_1</b>
      <ul>
      <li>Grade Percentage: 6</li>
      <li>Your solution failed this test case! taking 0.070 sec</Li>
<li><pre>IndentationError: expected an indented block (<tested-program>, line 29)</pre></li>
<li><pre>Traceback (most recent call last):
  File "/Users/lord_pretzel/.pyenv/versions/3.9.0/lib/python3.9/site-packages/grader-0.0.1-py3.9.egg/grader/execution_base.py", line 60, in call_test_function
    test_function(
  File "/Users/lord_pretzel/.pyenv/versions/3.9.0/lib/python3.9/site-packages/grader-0.0.1-py3.9.egg/grader/core.py", line 47, in wrapper
    raise module.caughtException
  File "/Users/lord_pretzel/.pyenv/versions/3.9.0/lib/python3.9/site-packages/grader-0.0.1-py3.9.egg/grader/program_container.py", line 38, in run
    self._exec_code()
  File "/Users/lord_pretzel/.pyenv/versions/3.9.0/lib/python3.9/site-packages/grader-0.0.1-py3.9.egg/grader/program_container.py", line 53, in _exec_code
    code = compile(source, "<tested-program>", "exec", dont_inherit=True)
  File "<tested-program>", line 29
    def add(self, x):
    ^
IndentationError: expected an indented block
</pre></li>
      </ul>
      </li>
      <li><b>test_key_heap_2</b>
      <ul>
      <li>Grade Percentage: 6</li>
      <li>Your solution failed this test case! taking 0.071 sec</Li>
<li><pre>IndentationError: expected an indented block (<tested-program>, line 29)</pre></li>
<li><pre>Traceback (most recent call last):
  File "/Users/lord_pretzel/.pyenv/versions/3.9.0/lib/python3.9/site-packages/grader-0.0.1-py3.9.egg/grader/execution_base.py", line 60, in call_test_function
    test_function(
  File "/Users/lord_pretzel/.pyenv/versions/3.9.0/lib/python3.9/site-packages/grader-0.0.1-py3.9.egg/grader/core.py", line 47, in wrapper
    raise module.caughtException
  File "/Users/lord_pretzel/.pyenv/versions/3.9.0/lib/python3.9/site-packages/grader-0.0.1-py3.9.egg/grader/program_container.py", line 38, in run
    self._exec_code()
  File "/Users/lord_pretzel/.pyenv/versions/3.9.0/lib/python3.9/site-packages/grader-0.0.1-py3.9.egg/grader/program_container.py", line 53, in _exec_code
    code = compile(source, "<tested-program>", "exec", dont_inherit=True)
  File "<tested-program>", line 29
    def add(self, x):
    ^
IndentationError: expected an indented block
</pre></li>
      </ul>
      </li>
      <li><b>test_key_heap_3</b>
      <ul>
      <li>Grade Percentage: 6</li>
      <li>Your solution failed this test case! taking 0.094 sec</Li>
<li><pre>IndentationError: expected an indented block (<tested-program>, line 29)</pre></li>
<li><pre>Traceback (most recent call last):
  File "/Users/lord_pretzel/.pyenv/versions/3.9.0/lib/python3.9/site-packages/grader-0.0.1-py3.9.egg/grader/execution_base.py", line 60, in call_test_function
    test_function(
  File "/Users/lord_pretzel/.pyenv/versions/3.9.0/lib/python3.9/site-packages/grader-0.0.1-py3.9.egg/grader/core.py", line 47, in wrapper
    raise module.caughtException
  File "/Users/lord_pretzel/.pyenv/versions/3.9.0/lib/python3.9/site-packages/grader-0.0.1-py3.9.egg/grader/program_container.py", line 38, in run
    self._exec_code()
  File "/Users/lord_pretzel/.pyenv/versions/3.9.0/lib/python3.9/site-packages/grader-0.0.1-py3.9.egg/grader/program_container.py", line 53, in _exec_code
    code = compile(source, "<tested-program>", "exec", dont_inherit=True)
  File "<tested-program>", line 29
    def add(self, x):
    ^
IndentationError: expected an indented block
</pre></li>
      </ul>
      </li>
      <li><b>test_key_heap_4</b>
      <ul>
      <li>Grade Percentage: 6</li>
      <li>Your solution failed this test case! taking 0.091 sec</Li>
<li><pre>IndentationError: expected an indented block (<tested-program>, line 29)</pre></li>
<li><pre>Traceback (most recent call last):
  File "/Users/lord_pretzel/.pyenv/versions/3.9.0/lib/python3.9/site-packages/grader-0.0.1-py3.9.egg/grader/execution_base.py", line 60, in call_test_function
    test_function(
  File "/Users/lord_pretzel/.pyenv/versions/3.9.0/lib/python3.9/site-packages/grader-0.0.1-py3.9.egg/grader/core.py", line 47, in wrapper
    raise module.caughtException
  File "/Users/lord_pretzel/.pyenv/versions/3.9.0/lib/python3.9/site-packages/grader-0.0.1-py3.9.egg/grader/program_container.py", line 38, in run
    self._exec_code()
  File "/Users/lord_pretzel/.pyenv/versions/3.9.0/lib/python3.9/site-packages/grader-0.0.1-py3.9.egg/grader/program_container.py", line 53, in _exec_code
    code = compile(source, "<tested-program>", "exec", dont_inherit=True)
  File "<tested-program>", line 29
    def add(self, x):
    ^
IndentationError: expected an indented block
</pre></li>
      </ul>
      </li>
      <li><b>test_key_heap_5</b>
      <ul>
      <li>Grade Percentage: 6</li>
      <li>Your solution failed this test case! taking 0.091 sec</Li>
<li><pre>IndentationError: expected an indented block (<tested-program>, line 29)</pre></li>
<li><pre>Traceback (most recent call last):
  File "/Users/lord_pretzel/.pyenv/versions/3.9.0/lib/python3.9/site-packages/grader-0.0.1-py3.9.egg/grader/execution_base.py", line 60, in call_test_function
    test_function(
  File "/Users/lord_pretzel/.pyenv/versions/3.9.0/lib/python3.9/site-packages/grader-0.0.1-py3.9.egg/grader/core.py", line 47, in wrapper
    raise module.caughtException
  File "/Users/lord_pretzel/.pyenv/versions/3.9.0/lib/python3.9/site-packages/grader-0.0.1-py3.9.egg/grader/program_container.py", line 38, in run
    self._exec_code()
  File "/Users/lord_pretzel/.pyenv/versions/3.9.0/lib/python3.9/site-packages/grader-0.0.1-py3.9.egg/grader/program_container.py", line 53, in _exec_code
    code = compile(source, "<tested-program>", "exec", dont_inherit=True)
  File "<tested-program>", line 29
    def add(self, x):
    ^
IndentationError: expected an indented block
</pre></li>
      </ul>
      </li>
      <li><b>test_median_1</b>
      <ul>
      <li>Grade Percentage: 13</li>
      <li>Your solution failed this test case! taking 0.091 sec</Li>
<li><pre>IndentationError: expected an indented block (<tested-program>, line 29)</pre></li>
<li><pre>Traceback (most recent call last):
  File "/Users/lord_pretzel/.pyenv/versions/3.9.0/lib/python3.9/site-packages/grader-0.0.1-py3.9.egg/grader/execution_base.py", line 60, in call_test_function
    test_function(
  File "/Users/lord_pretzel/.pyenv/versions/3.9.0/lib/python3.9/site-packages/grader-0.0.1-py3.9.egg/grader/core.py", line 47, in wrapper
    raise module.caughtException
  File "/Users/lord_pretzel/.pyenv/versions/3.9.0/lib/python3.9/site-packages/grader-0.0.1-py3.9.egg/grader/program_container.py", line 38, in run
    self._exec_code()
  File "/Users/lord_pretzel/.pyenv/versions/3.9.0/lib/python3.9/site-packages/grader-0.0.1-py3.9.egg/grader/program_container.py", line 53, in _exec_code
    code = compile(source, "<tested-program>", "exec", dont_inherit=True)
  File "<tested-program>", line 29
    def add(self, x):
    ^
IndentationError: expected an indented block
</pre></li>
      </ul>
      </li>
      <li><b>test_median_2</b>
      <ul>
      <li>Grade Percentage: 13</li>
      <li>Your solution failed this test case! taking 0.068 sec</Li>
<li><pre>IndentationError: expected an indented block (<tested-program>, line 29)</pre></li>
<li><pre>Traceback (most recent call last):
  File "/Users/lord_pretzel/.pyenv/versions/3.9.0/lib/python3.9/site-packages/grader-0.0.1-py3.9.egg/grader/execution_base.py", line 60, in call_test_function
    test_function(
  File "/Users/lord_pretzel/.pyenv/versions/3.9.0/lib/python3.9/site-packages/grader-0.0.1-py3.9.egg/grader/core.py", line 47, in wrapper
    raise module.caughtException
  File "/Users/lord_pretzel/.pyenv/versions/3.9.0/lib/python3.9/site-packages/grader-0.0.1-py3.9.egg/grader/program_container.py", line 38, in run
    self._exec_code()
  File "/Users/lord_pretzel/.pyenv/versions/3.9.0/lib/python3.9/site-packages/grader-0.0.1-py3.9.egg/grader/program_container.py", line 53, in _exec_code
    code = compile(source, "<tested-program>", "exec", dont_inherit=True)
  File "<tested-program>", line 29
    def add(self, x):
    ^
IndentationError: expected an indented block
</pre></li>
      </ul>
      </li>
      <li><b>test_median_3</b>
      <ul>
      <li>Grade Percentage: 14</li>
      <li>Your solution failed this test case! taking 0.089 sec</Li>
<li><pre>IndentationError: expected an indented block (<tested-program>, line 29)</pre></li>
<li><pre>Traceback (most recent call last):
  File "/Users/lord_pretzel/.pyenv/versions/3.9.0/lib/python3.9/site-packages/grader-0.0.1-py3.9.egg/grader/execution_base.py", line 60, in call_test_function
    test_function(
  File "/Users/lord_pretzel/.pyenv/versions/3.9.0/lib/python3.9/site-packages/grader-0.0.1-py3.9.egg/grader/core.py", line 47, in wrapper
    raise module.caughtException
  File "/Users/lord_pretzel/.pyenv/versions/3.9.0/lib/python3.9/site-packages/grader-0.0.1-py3.9.egg/grader/program_container.py", line 38, in run
    self._exec_code()
  File "/Users/lord_pretzel/.pyenv/versions/3.9.0/lib/python3.9/site-packages/grader-0.0.1-py3.9.egg/grader/program_container.py", line 53, in _exec_code
    code = compile(source, "<tested-program>", "exec", dont_inherit=True)
  File "<tested-program>", line 29
    def add(self, x):
    ^
IndentationError: expected an indented block
</pre></li>
      </ul>
      </li>
      <li><b>test_topk_students</b>
      <ul>
      <li>Grade Percentage: 30</li>
      <li>Your solution failed this test case! taking 0.083 sec</Li>
<li><pre>IndentationError: expected an indented block (<tested-program>, line 29)</pre></li>
<li><pre>Traceback (most recent call last):
  File "/Users/lord_pretzel/.pyenv/versions/3.9.0/lib/python3.9/site-packages/grader-0.0.1-py3.9.egg/grader/execution_base.py", line 60, in call_test_function
    test_function(
  File "/Users/lord_pretzel/.pyenv/versions/3.9.0/lib/python3.9/site-packages/grader-0.0.1-py3.9.egg/grader/core.py", line 47, in wrapper
    raise module.caughtException
  File "/Users/lord_pretzel/.pyenv/versions/3.9.0/lib/python3.9/site-packages/grader-0.0.1-py3.9.egg/grader/program_container.py", line 38, in run
    self._exec_code()
  File "/Users/lord_pretzel/.pyenv/versions/3.9.0/lib/python3.9/site-packages/grader-0.0.1-py3.9.egg/grader/program_container.py", line 53, in _exec_code
    code = compile(source, "<tested-program>", "exec", dont_inherit=True)
  File "<tested-program>", line 29
    def add(self, x):
    ^
IndentationError: expected an indented block
</pre></li>
      </ul>
      </li>
    </ul>
  </body>
</html>
